name: PR Actions

on:
  pull_request:
    branches:
      - main
      - dev

env:
  CI: true

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install NPM Dependencies
        run: yarn install
      - name: Run Build
        run: yarn nx run-many --target=build --all --configuration=production
      - name: Run Linting
        run: yarn nx affected --target=lint --base=${{ github.base_ref }}
      - name: Run Unit & Integration Tests
        run: yarn nx affected --target=test --base=${{ github.base_ref }}
      # - name: Install Playwright Dependencies
      #   run: sudo npx playwright install-deps
      # - name: Run End-to-End Tests
      #   run: yarn test:e2e
